### ISSUE TITLE
How to perform pull request?

### ISSUE THREAD

**Issue by Cli98** [BitTigerInst/VIPService-G04#1]
I have tried my best, but still failed to pull my code into folder...

Just stuck into "compare" step.

Can anyone help? appreciate much.

**Comment by Cli98** [comment]
Ok this one has been done.

I should fork the folder first and then create sub-forder in the forked one.

Finally perform pull request.

Wish this could help someone who did not pull their files yet.

**Comment by cc13ny** [comment]
It seems that you have successfully updated the README.md. What does the “compare” step mean?

**Comment by cc13ny** [comment]
What Cli98 said is right. We need a small meeting for instructions of Git.
